FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
COPY docs/ /app/docs/


# استفاده از mirror Runflare
#RUN pip install --no-cache-dir -i https://mirror.abrha.net/repository/pypi/simple/ -r requirements.txt
RUN pip install --no-cache-dir -i https://mirror.abrha.net/repository/pypi/simple/ -r requirements.txt
COPY . .

EXPOSE 8000

CMD ["streamlit", "run", "app.py", "--server.port=8000", "--server.address=0.0.0.0"]
